autobuilder: add build queue (lays foundation for build injection)

diff --git a/autobuilder b/autobuilder
--- a/autobuilder
+++ b/autobuilder
@@ -11,6 +11,8 @@ CONFIG_FILE_PATH="/etc/autobuilder.ini"
 # These are relative to $WORKDIR, and are set after config parsing
 LAST_BUILT_LOG="$(basename $0)-lastbuilt.txt"
 EVENT_QUEUE="$(basename $0)-$$-eventqueue.txt"
+BUILD_QUEUE="$(basename $0)-$$-buildqueue.txt"
+REPORT_QUEUE="$(basename $0)-$$-reportqueue.txt"
 
 # Read in from the configuration file
 MACHINE_POOL=
@@ -168,20 +170,20 @@ show_machine_queue() {
 
 # $1 -- revision
 # $2 -- ip address
-# $3 -- build id number
+# $3 -- build script
 push_build_to_runner_machine() {
    local current_rev=
    local ip=
-   local build_id=
+   local build_script=
    local jobcmd=
 
    test "x$1" = "x" && return 1 || current_rev="$1"
    test "x$2" = "x" && return 1 || ip="$2"
-   test "x$3" = "x" && return 1 || build_id="$3"
+   test "x$3" = "x" && return 1 || build_script="$3"
 
    # HACK!
    local myip=10.0.0.186
-   jobcmd="$JOBRUNNER_PATH add $current_rev $myip:${BUILD_SCRIPT[$build_id]} $myip:/foo/bar/baz"
+   jobcmd="$JOBRUNNER_PATH add $current_rev $myip:$build_script $myip:/foo/bar/baz"
    dbg "Asking $REMOTE_USER@$ip to execute job command $jobcmd"
    pmrpc_run_command $REMOTE_USER $ip "$jobcmd"
 }
@@ -241,35 +243,75 @@ do_tree_scan() {
          continue
       fi
 
-      # Select which machine in the pool should execute the build
-      if runner=$(pick_runner_machine)
+      # Add the build to the queue for processing
+      if enqueue_build "$i" "$current_revision"
       then
-         logts "Selected $runner to execute build"
-         show_machine_queue $runner
+         dbg "Revision $current_revision of ${BUILD_TITLE[$i]} queued for pushing out to the pool"
       else
-         err "Failed to select a runner machine from pool: $MACHINE_POOL"
+         err "Failed to enqueue rev. $current_revision of ${BUILD_TITLE[$i]}"
+      fi
+   done
+}
+
+# Add a build the the build queue for passing out to the
+# machine pool for processing.  The actual push process is
+# carried out via. process_build_queue().
+# $1 -- build id
+# $2 -- build revision
+enqueue_build() {
+   test "x$1" = "x" && return 1
+   test "x$2" = "x" && return 2
+
+   queue_lock "$BUILD_QUEUE"
+   queue_add "$BUILD_QUEUE"  "$1@$2"
+   queue_unlock "$BUILD_QUEUE"
+}
+
+# Pass each entry in the build queue out to the machine pool for execution
+process_build_queue() {
+   local runner=
+   local buildspec=
+   local ret=0
+   local id=
+   local rev=
+
+   while true
+   do
+      # Pop a buildspec off the queue
+      queue_lock "$BUILD_QUEUE"
+      buildspec=$(queue_pop_eldest "$BUILD_QUEUE")
+      queue_unlock "$BUILD_QUEUE"
+      id="$(echo $buildspec | cut -d"@" -f1)"
+      rev="$(echo $buildspec | cut -d"@" -f2)"
+
+      # If we didn't get a spec we're at the end of the queue...
+      test -n "$rev" && test -n "$id" || break
+
+      # Select which machine in the pool should execute the build
+      if ! runner=$(pick_runner_machine)
+      then
+         err "Failed to select machine to run ${BUILD_TITLE[$id]} revision $rev"
+         ret=$((ret+1))
          continue
       fi
 
       # Push the build out
-      if push_build_to_runner_machine $current_revision $runner $i
+      if push_build_to_runner_machine "$rev" $runner "${BUILD_SCRIPT[$id]}"
       then
-         logts "Scheduled build $current_revision on $runner"
-         set_last_build_revision "${BUILD_TITLE[$i]}" "$current_revision"
+         logts "${BUILD_TITLE[$id]} revision $rev to be processed by runner $runner"
+         set_last_build_revision "${BUILD_TITLE[$id]}" "$current_revision"
       else
-         err "Failed to add ${BUILD_TITLE[$i]} build to runner $runner"
+         err "Failed to push ${BUILD_TITLE[$id]} revision $rev build to runner $runner"
+         ret=$((ret+1))
          continue
       fi
    done
+   return $ret
 }
 
 #
 # Entry point
 #
-
-# Clean up after ourselves...
-trap "rm -f $BUILD_QUEUE $EVENT_QUEUE" EXIT
-
 while getopts $CARGS opt
 do
    case $opt in
@@ -287,15 +329,27 @@ parse_configuration || die "Failed to parse configuration $CONFIG_FILE_PATH"
 # Set up paths for workdir files
 LAST_BUILT_LOG="${WORKDIR}/${LAST_BUILT_LOG}"
 EVENT_QUEUE="${WORKDIR}/${EVENT_QUEUE}"
+BUILD_QUEUE="${WORKDIR}/${BUILD_QUEUE}"
+REPORT_QUEUE="${WORKDIR}/${REPORT_QUEUE}"
+
+# Ensure we clean up after ourselves...
+trap "rm -f $BUILD_QUEUE $EVENT_QUEUE $REPORT_QUEUE" EXIT
 
 while true
 do
    # Wait for an input event
    if event=$(event_blocking_read $EVENT_QUEUE)
    then
+      dbg "New event: $event"
       case $event in
          DOSCAN) do_tree_scan ;;
          *) err "Unrecognised input event \"$event\"" ;;
       esac
+   fi
+
+   # Process the build queue
+   if ! process_build_queue
+   then
+      err "Errors processing the build queue -- some builds may be dropped :-("
    fi
 done
