autobuilder: add reporting path

diff --git a/autobuilder b/autobuilder
--- a/autobuilder
+++ b/autobuilder
@@ -457,12 +457,138 @@ process_build_queue() {
    return $ret
 }
 
+process_report_queue() {
+   local report=
+   local ret=0
+   local build_title=
+   local build_revision=
+   local build_runner=
+   local build_result=
+   local build_report=
+   local inflight=
+
+   while true
+   do
+      queue_lock "$REPORT_QUEUE"
+      report="$(queue_pop_eldest "$REPORT_QUEUE")"
+      queue_unlock "$REPORT_QUEUE"
+
+      # Empty result means the queue is empty
+      test "x$report" = "x" && break
+
+      build_title=$(reportstring_to_build_title "$report")
+      build_revision=$(reportstring_to_revision "$report")
+      build_runner=$(reportstring_to_runner_ip "$report")
+      build_result=$(reportstring_to_result "$report")
+      build_report=$(reportstring_to_report_path "$report")
+
+      logts "Runner $build_runner reported $build_result for $build_title revision $build_revision"
+
+      # Find this build in our "in flight" build list
+      if ! inflight=$(lookup_inflight_build_by_revision "$build_revision")
+      then
+         err "Couldn't locate build on inflight list -- reports will be dropped :-("
+         ret=$((ret+1))
+         continue
+      fi
+
+      # Remove from the inflight list
+      if ! remove_build_from_inflight_list "$build_title" "$build_revision"
+      then
+         err "Failed to remove build from inflight list"
+         ret=$((ret+1))
+         continue
+      fi
+
+      logts "TODO: email results"
+   done
+   dbg "Finished processing report queue"
+   return $ret
+}
+
+# $1 -- build title
+# $2 -- revision
+# $3 -- runner ip
+# $4 -- result
+# $5 -- report path
+report_to_queuestring() {
+   test "x${1}" = "x" && return 1
+   test "x${2}" = "x" && return 1
+   test "x${3}" = "x" && return 1
+   test "x${4}" = "x" && return 1
+   test "x${5}" = "x" && return 1
+
+   if test "${4}" != "SUCCESS" && test "${4}" != "FAILURE"
+   then
+      return 1
+   fi
+
+   #__check_path "$5" || return 1
+   __is_dotted_quad "$3" || return 1
+
+   echo "${1}@${2}@${3}@${4}@${5}"
+}
+
+# $1 -- report string
+reportstring_to_build_title() {
+   test "x${1}" = "x" && return 1
+   echo "${1}" | cut -d"@" -f1
+}
+
+# $1 -- report string
+reportstring_to_revision() {
+   test "x${1}" = "x" && return 1
+   echo "${1}" | cut -d"@" -f2
+}
+
+# $1 -- report string
+reportstring_to_runner_ip() {
+   local s=
+   test "x${1}" = "x" && return 1
+   s=$(echo "${1}" | cut -d"@" -f3)
+   __is_dotted_quad "$s" && echo "$s"
+}
+
+# $1 -- report string
+reportstring_to_result() {
+   local s=
+   test "x${1}" = "x" && return 1
+   s=$(echo "${1}" | cut -d"@" -f4)
+   if test "${s}" = "SUCCESS" || test "${s}" = "FAILURE"
+   then
+      echo $s
+   fi
+}
+
+# $1 -- report string
+reportstring_to_report_path() {
+   local s=
+   test "x${1}" = "x" && return 1
+   s=$(echo "${1}" | cut -d"@" -f5)a
+   #__check_path "$s" && echo "$s"
+}
+
 # Add a build result to the reporting queue
 report_result() {
-   # TODO: check input string
+   local s=
+
+   if ! s=$(report_to_queuestring "$1" "$2" "$3" "$4" "$5")
+   then
+      err "Failed to convert inputs to a report string"
+      return 1
+   fi
+
+   # Add the report to the report queue
    queue_lock "$REPORT_QUEUE"
-   queue_add "$@"
+   if ! queue_add "$REPORT_QUEUE" "$s"
+   then
+      err "Failed to add report into report queue"
+      queue_unlock "$REPORT_QUEUE"
+      return 1
+   fi
    queue_unlock "$REPORT_QUEUE"
+
+   # Generate a report ready event for the master
    event_write "$EVENT_QUEUE" "$EVENT_ID_BUILD_REPORT_READY"
 }
 
@@ -507,7 +633,7 @@ REPORT_QUEUE="${WORKDIR}/${REPORT_QUEUE}"
 case $1 in
    scan) request_revision_scan ;;
    requestbuild) shift; request_build "$@" ;;
-   report) shift; report_result "$@" ;;
+   report) shift; report_result $@ ;;
    run)
       # Ensure we clean up after ourselves...
       trap "rm -f $BUILD_QUEUE $EVENT_QUEUE $REPORT_QUEUE" EXIT
